version: '3.4'

services:
  database:
    image: postgres:alpine
    container_name: pg_container
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - '5432:5432'
    volumes:
       - pgdata:/var/lib/postgresql/data
    restart: always

  gifoff:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    env_file: .env
    environment:
      NODE_ENV: production
      DB_HOST: database
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: example
      DB_NAME: postgres
    ports:
      - 1400:1400
    links:
     - database
    depends_on:
      - database

volumes:
    pgdata:
      driver: local